language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  
  #tagging
  - docker tag udagram-api-feed caoken/udagram-api-feed:v1
  - docker tag udagram-api-user caoken/udagram-api-user:v1
  - docker tag udagram-frontend caoken/udagram-frontend:v1
  - docker tag udagram-reverseproxy caoken/udagram-reverseproxy:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - docker login -u caoken -p Tiendungcao7777
  - docker push caoken/udagram-api-feed:v1
  - docker push caoken/udagram-api-user:v1
  - docker push caoken/udagram-frontend:v1
  - docker push caoken/udagram-reverseproxy:v1