apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-user
  name: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api-user
  template:
    metadata:
      labels:
        service: api-user
    spec:
      containers:
      - name: api-user
        image: caoken/udagram-api-user:v1
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"      
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret
      restartPolicy: Always